title: Andpact
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin: "dark" # Other options include "air", "aqua", "contrast", "dirt", "neon", "mint", "plum", "sunrise"

enable_copy_code_button: true

plugins:
  - jekyll-include-cache

# author:
#   name   : "Andpact"
#   avatar : "/assets/images/avatar.jpg"
#   bio    : "Programmer"

defaults:
  # 게시글
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar:
        nav: sidebar

  # 일반 페이지 (카테고리 포함)
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: sidebar